### ISSUE TITLE
ZMQ_REQ_RELAXED + ZMQ_REQ_CORRELATE = no reply

### ISSUE THREAD

**Issue by jiggersplat** [zeromq/jeromq#442]
When I set both options, my replies are being discarded. If I set only the ZMQ_REQ_RELAXED options, I am able to receive replies.

socket.setReqCorrelate(true);
socket.setReqRelaxed(true);
socket.connect(addr);
socket.send(mymsg);
bytes[] reply = socket.recv() // hangs

**Comment by fredoboulo** [comment]
It seems to me that zmq.socket.reqrep.TestReqCorrelateRelaxed already tests that case.

**Comment by daveyarwood** [comment]
@jiggersplat Are you experiencing this issue with the latest version of JeroMQ?

**Comment by jiggersplat** [comment]
I have not had a chance to try it with the latest version. The change making the socket class final forced some refactorization that I have not had the time to do yet.

**Comment by daveyarwood** [comment]
FWIW, I think that change has been undone -- see https://github.com/zeromq/jeromq/issues/446 / https://github.com/fredoboulo/jeromq/commit/a8e715ee35a63fb8c9e356cf2628c5dedb669382#diff-ab533440049bba1d9014953971332f9aR410.

**Comment by jiggersplat** [comment]
Maybe I'm doing something wrong... here's the code I'm running with 0.4.3-SNAPSHOT. It seems like I probably need to set Relaxed and Correlated on the reply socket as well, but I get `java.lang.IllegalArgumentException: Unknown Option 52` or `53` when I try to do that. This example hangs on the second requestSocket.send() call.

	@Test
	public void relaxedAndCorrelatedTest() {

		// create a logger
		org.slf4j.Logger log = LoggerFactory.getLogger("RelaxedCorrelatedTest");

		// create a zmq context
		ZMQ.Context context = ZMQ.context(1);

		// start a thread for the reply socket
		new Thread() {
			public void run() {
				log.debug("Starting reply socket thread");
				ZMQ.Socket replySocket = context.socket(ZMQ.REP);
				replySocket.bind("inproc://EwbmRequestSocketTest");

				// receive the first request without sending a reply
				log.debug("Received request");
				replySocket.recv();

				// receive the next request
				log.debug("Received request");
				byte[] bytes = replySocket.recv();

				// echo it back
				log.debug("Sending reply");
				replySocket.send(bytes);
			}
		}.start();

		// create and connect the request socket
		ZMQ.Socket requestSocket = context.socket(ZMQ.REQ);
		requestSocket.connect("inproc://RelaxedCorrelatedTest");
		requestSocket.setReqCorrelate(true);
		requestSocket.setReqRelaxed(true);
		requestSocket.setReceiveTimeOut(1000);

		// send the first request
		log.debug("Sending first message, expecting timeout");
		requestSocket.send(("Hello").getBytes());

		// wait for the first reply
		log.debug("Waiting for reply");
		byte[] bytes = requestSocket.recv();

		if (bytes == null) {
			log.debug("Timeout, no reply received");
		}

		// the first request should timeout and return null
		assertTrue(bytes == null);

		// send the second request
		log.debug("Sending second message");
		requestSocket.send(("Goodbye").getBytes());

		// wait for the second reply
		log.debug("Waiting for reply");
		bytes = requestSocket.recv();
		String reply = new String(bytes);
		log.debug("Got reply: \"" + reply + "\"");

		assertTrue(reply.equals("Goodbye"));
	}

**Comment by fredoboulo** [comment]
Thanks for putting some more code, that helped me to find out the cause of your hanging in send(). FYI a fix was made in libzmq but is not present in 4.1 which was used for the latest Jeromq version...

Correlate and Relaxed options are specific to REQ sockets, so their use in your code is correct according to me.

The 2 sockets are not referring to the same endpoint, you could change your line
```
			replySocket.bind("inproc://EwbmRequestSocketTest");
```
to 
```
			replySocket.bind("inproc://RelaxedCorrelatedTest");
```
to start the cycle of request-replies.

I understand it is used to demonstrate a slow REP server, is it correct to assume that?

**Comment by jiggersplat** [comment]
Doh. May have been a copy-paste error, but I will check and make sure I have the correct endpoints when I get a chance. Yes, the thread is simulating a failure on the first reply. If I understand correctly, using correlated/relaxed should allow me to continue using the sockets without resetting the connection.

**Comment by fredoboulo** [comment]
I'm not overly using this option, so what I'm about to say is mostly what I read in the tests...

According to [this part of the test](https://github.com/zeromq/jeromq/blob/master/src/test/java/zmq/socket/reqrep/TestReqRelaxed.java#L67), the reply to the first request should be discarded. This test is the adaptation of an existing one in libzmq, so I assume this is part of the canon.
Apart from that, the rest of the test checks behaviour with several connected REP sockets, making round-robin amongst them. I'm not sure if the behaviour of one REP "forgetting" to reply is part of acceptable scenarii.
When playing with your code, I made two variations: one with 2 REP sockets connected (one bogus one correct), another with one REP like yours but with a SLOW reply and it works well in both cases.

**Comment by fredoboulo** [comment]
Hi @jiggersplat: was your problem solved by 0.4.3? May this issue be closed?

**Comment by jiggersplat** [comment]
It is still not behaving as I expect, although it could be that my expectations are wrong.

The second call to recv() now returns null. I ran it through the debugger and it looks like when it gets to Dealer.java::recvpipe(ValueReference<Pipe> pipe), pipe is null.

**Comment by fredoboulo** [comment]
Hi,

Is it part of the normal behaviour of your application that a REP forgets to answer, without the socket being closed? It is part of your test, on the comment "receive the first request without sending a reply".

I'm not aware of this as an acceptable use case for ZMQ.

**Comment by jiggersplat** [comment]
No, it is not part of normal behavior. I was hoping to use these features to recover from unexpected disconnects in the middle of a req/rep cycle without using timeouts and closing and re-opening the connection.

**Comment by Nik-Novak** [comment]
This is still an issue. Sockets drop all connections regardless of ID
