### ISSUE TITLE
xSub socket subscription throws IllegalArgumentException

### ISSUE THREAD

**Issue by komape** [zeromq/jeromq#916]
My system has a broker with two sockets, one xPub and one xSub. When I try to subscribe the xSub socket to all topics I get an `IllegalArgumentException` with the error message `Unknown Option 6`. It looks like that the subscription command is internally mapped to the number 6. But there is no switch case option that handles the number 6.

```java
ZMQ.Socket xSubSocket = context.createSocket(SocketType.XSUB);
xSubSocket.bind(X_SUB_ADDRESS);
xSubSocket.subscribe(""); // subscribe to all
```

```bash
Exception in thread "main" java.lang.IllegalArgumentException: Unknown Option 6
	at zmq.Options.setSocketOpt(Options.java:547)
	at zmq.SocketBase.setSocketOpt(SocketBase.java:234)
	at org.zeromq.ZMQ$Socket.setSocketOpt(ZMQ.java:910)
	at org.zeromq.ZMQ$Socket.subscribe(ZMQ.java:2113)
```

What's the recommended way to handle this?

**Comment by Muspah** [comment]
Bit late, but calling subscribe on an XSUB socket doesn't work indeed. We've fixed it like:

```
for (String sub : subscriptions) {
    ByteArrayOutputStream bos = new ByteArrayOutputStream();
    bos.writeBytes(new byte[]{0x01});
    bos.writeBytes(sub.getBytes(StandardCharsets.UTF_8));
    socket.send(bos.toByteArray());
}
```

**Comment by lavajuno** [comment]
Looks like this issue still exists in v0.6.0. Something similar to what @Muspah provided would be a good way to properly implement Socket.subscribe().
